language: node_js

node_js: "6"

addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - libdbus-1-dev
      - libglib2.0-dev
      - dbus

before_install:
  - cd debian/

script:
  - yarn build

cache:
  directories:
  - debian/node_modules

deploy:
  provider: packagecloud
  repository: "headset-electron"
  username: "headsetapp"
  token: "${PACKAGECLOUD_TOKEN}"
  dist: "ubuntu/trusty"
  on:
    branch: deploy-script
