language: node_js

node_js: "6"

addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
      - libdbus-1-dev
      - libglib2.0-dev
      - dbus

before_install:
  - cd linux/

script:
  - yarn build

git:
  depth: 3

cache:
  yarn: true
  directories:
  - linux/node_modules
