language: node_js

node_js: "6"

addons:
  apt:
    packages:
      - fakeroot
      - dpkg
      - rpm
      - libdbus-1-dev
      - libglib2.0-dev
      - dbus

before_install:
  - cd debian/

script:
  - yarn build

cache:
  directories:
  - debian/node_modules

deploy:
  - provider: packagecloud
    repository: "headset-electron"
    username: "headsetapp"
    token: "${PACKAGECLOUD_TOKEN}"
    dist: "ubuntu/trusty"
    local_dir: build/installers
    package_glob: "*.deb"
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: packagecloud
    repository: "headset-electron"
    username: "headsetapp"
    token: "${PACKAGECLOUD_TOKEN}"
    dist: "fedora/26"
    local_dir: build/installers
    package_glob: "*.rpm"
    skip_cleanup: true
    on:
      branch: master
      tags: true
